const KEY="nbpt:v1";const $=id=>document.getElementById(id);let state=load();
function load(){try{return JSON.parse(localStorage.getItem(KEY))||{schema:"nbpt.dataset/v1",entries:[]}}catch{return{schema:"nbpt.dataset/v1",entries:[]}}}
function save(){localStorage.setItem(KEY,JSON.stringify(state));render()}
function csv(v){return v.split(",").map(x=>x.trim()).filter(Boolean).slice(0,30)}
function base(kind){return{id:crypto.randomUUID(),kind,case_id:$("caseId").value.trim(),relative_day:Number($("studyDay").value),recorded_at:new Date().toISOString()}}
["painNow","painWorst","interference","function","mood"].forEach(id=>{$(id).addEventListener("input",()=>$(id+"Out").value=$(id).value)})
$("dailyForm").addEventListener("submit",e=>{e.preventDefault();state.entries.push({...base("DAILY"),source_class:"PATIENT_REPORT",pain_now:+$("painNow").value,pain_worst:+$("painWorst").value,pain_interference:+$("interference").value,function:+$("function").value,mood:+$("mood").value,sleep_hours:$("sleep").value===""?null:+$("sleep").value,withdrawal_symptoms:csv($("withdrawal").value),adverse_effects:csv($("adverse").value),activities_completed:$("completed").value.trim(),activities_prevented:$("prevented").value.trim(),urgent_care:$("urgentCare").checked,uncertainty:$("uncertainty").value.trim()});save();$("studyDay").value=+$("studyDay").value+1;e.target.reset()})
$("eventForm").addEventListener("submit",e=>{e.preventDefault();state.entries.push({...base("EVENT"),event_type:$("eventType").value,source_class:$("evidenceClass").value,description:$("eventDescription").value.trim(),uncertainty:$("eventUncertainty").value.trim()});save();e.target.reset()})
function mean(a,k){const v=a.map(x=>x[k]).filter(Number.isFinite);return v.length?(v.reduce((s,x)=>s+x,0)/v.length).toFixed(1):"—"}
function render(){const all=[...state.entries].sort((a,b)=>a.relative_day-b.relative_day||a.recorded_at.localeCompare(b.recorded_at)),d=all.filter(x=>x.kind==="DAILY"),missing=d.filter(x=>x.sleep_hours===null).length;$("count").textContent=all.length+" records";$("summary").innerHTML=[["N",d.length],["Mean pain",mean(d,"pain_now")],["Mean interference",mean(d,"pain_interference")],["Missing sleep",missing]].map(([a,b])=>`<div class="metric"><span>${a}</span><strong>${b}</strong></div>`).join("");$("ledger").innerHTML=all.slice().reverse().map(x=>`<article class="entry"><span class="tag">${escapeHtml(x.kind==="EVENT"?x.event_type:x.source_class)}</span> <strong>Day ${x.relative_day}</strong><p>${escapeHtml(x.kind==="EVENT"?x.description:`Pain ${x.pain_now}/10 · interference ${x.pain_interference}/10 · function ${x.function}/10`)}</p><small>Uncertainty: ${escapeHtml(x.uncertainty)}</small></article>`).join("")||"<p>No observations yet.</p>";draw(d)}
function escapeHtml(s=""){return s.replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]))}
function draw(data){const c=$("chart"),x=c.getContext("2d");x.clearRect(0,0,c.width,c.height);x.strokeStyle="#aab5af";x.beginPath();x.moveTo(45,20);x.lineTo(45,320);x.lineTo(980,320);x.stroke();if(!data.length)return;const days=data.map(v=>v.relative_day),min=Math.min(...days),max=Math.max(...days),px=d=>45+(d-min)/(max-min||1)*935,py=v=>320-v/10*290;[["pain_now","#c93d1e"],["pain_interference","#6f4bd8"],["function","#16775a"]].forEach(([k,col])=>{x.strokeStyle=col;x.lineWidth=3;x.beginPath();data.forEach((v,i)=>{const a=px(v.relative_day),b=py(v[k]);i?x.lineTo(a,b):x.moveTo(a,b)});x.stroke()})}
$("refresh").onclick=render;$("exportJson").onclick=()=>{const blob=new Blob([JSON.stringify(state,null,2)],{type:"application/json"}),a=document.createElement("a");a.href=URL.createObjectURL(blob);a.download=`pain-tracker-${$("caseId").value}.json`;a.click();URL.revokeObjectURL(a.href)}
$("importJson").onchange=async e=>{const v=JSON.parse(await e.target.files[0].text());if(v.schema!=="nbpt.dataset/v1"||!Array.isArray(v.entries))throw Error("Unsupported dataset");state=v;save()}
$("clearData").onclick=()=>{if(confirm("Permanently delete all tracker data from this browser?")){state={schema:"nbpt.dataset/v1",entries:[]};save()}}
render();
